### ISSUE TITLE
 How do you view the JUnit report.xml file?

### ISSUE THREAD

**Issue by runtimevic** [PeterZerlauth/Testing#3]
Hello @PeterZerlauth ,
 How do you view the JUnit report.xml file?
I am using this:
https://lotterfriends.github.io/online-junit-parser/#suite.2
Can you suggest me how you visualize it?
thanks you...

**Comment by PeterZerlauth** [comment]
![grafik](https://user-images.githubusercontent.com/48495545/226112009-5e6c5326-249f-4ae4-b13b-45ab32d3a218.png)

My Azure Pipeline has some Result view.

**Comment by runtimevic** [comment]
> ![grafik](https://user-images.githubusercontent.com/48495545/226112009-5e6c5326-249f-4ae4-b13b-45ab32d3a218.png)
> 
> My Azure Pipeline has some Result view. A Visual Studio plugin would also be nice, maybe i will have some time in the future

Can you explain what are the steps to follow to obtain this visualization with Azure Pipeline?
thanks you, Víctor.

**Comment by PeterZerlauth** [comment]
I have setup an "azure self hosted agent" (https://dev.azure.com/) on a Beckhoff C6015,
If i run my pipeline the repo will downloaded and build, then the testrun starts,
after that the results where published and released

https://github.com/PeterZerlauth/Testing/blob/master/azure-pipelines-release.yml

**Comment by runtimevic** [comment]
> I have setup an "azure self hosted agent" (https://dev.azure.com/) on a Beckhoff C6015,
> If i run my pipeline the repo will downloaded and build, then the testrun starts,
> after that the results where published and released
> 
> https://github.com/PeterZerlauth/Testing/blob/master/azure-pipelines-release.yml
> 
> To build and run the Twincat project, you need powershell or a c# app

Hello @PeterZerlauth 
Can you make a small guide or video to see and understand the steps to follow?  It would be great, thanks for everything...

**Comment by PeterZerlauth** [comment]
Its not a big deal, and the documentation is already realy nice, a lot of youtube videos ....
https://learn.microsoft.com/en-us/azure/devops/get-started/?view=azure-devops
https://www.jenkins.io/doc/
