### ISSUE TITLE
Add ability to choose continue or abort on failed assert

### ISSUE THREAD

**Issue by mark-lazarides** [PeterZerlauth/Testing#5]
When creating a test suite, we should be able to choose whether a failed assert causes an abort of the test.

**Comment by mark-lazarides** [comment]
@PeterZerlauth , I added a PR with a property in response to this issue  Happy to refactor that from your comments

**Comment by PeterZerlauth** [comment]
![image](https://github.com/PeterZerlauth/Testing/assets/48495545/63c2ed06-8c03-4b92-84d6-ffac5d6ec93d)

Refactored it a litle for future use

**Comment by PeterZerlauth** [comment]
Done

**Comment by PeterZerlauth** [comment]
done
